### ISSUE TITLE
prevent sensivity reset

### ISSUE THREAD

**Issue by LastExceed** [PGGB/DeviceChangeFix#2]
would it be possible to also fix the joystick sensivity resetting to 55 every time the controller reconnects?

also can you explain what "Bypass plugin logic" does?

thank you so much for making this plugin. this bug has annoyed the hell out of me and cost me several raid wipes

**Comment by PGGB** [comment]
> would it be possible to also fix the joystick sensivity resetting to 55 every time the controller reconnects?

Possibly, I don't know about this bug and I'm not currently subbed, but I can check it out once I am.

> also can you explain what "Bypass plugin logic" does?

That's just a checkmark to disable the fix temporarily. I added it in case the game uses the device change messages for something other than controllers, though I do not believe so.

**Comment by JupiterJesus** [comment]
I second the request. It doesn't always happen, though. I play it through Steam (as a non-steam game shortcut), so the controller I use is the virtual XInput controller that Steam creates. The actual controller I use varies (DS5 wired, DS5 wireless, DS4 wireless, XBox Elite wireless), but it always appears within FFXIV as an xbox controller because of Steam. 

I think the reset to 55 happens when I start the game with a different controller. For example, I've been using my DS5 wired, but today I decided to pair it with my PC with bluetooth. The sensitivity reset to 55 today right after that, even though nothing else changed. 

On a side note, I don't know how to install this plugin now since it doesn't appear in the Dalamud plugin list. I disabled the XBox Game Pass  "Xvdd SCSI Miniport", because people reported that the constant connection and disconnection of virtual game drives is what drives FFXIV crazy. It seems to have solved the problem temporarily, but it also means I can't play any xbox games on PC unless I re-enable. If this plugin can help, I'd really like to try it.

**Comment by PGGB** [comment]
> On a side note, I don't know how to install this plugin now since it doesn't appear in the Dalamud plugin list. 

It is currently only available if you opt-in for testing plugins. But since I haven't heard of any issues, I just made a PR to move it to stable. It should be available shortly for everyone.

**Comment by JupiterJesus** [comment]
Awesome, I popped in for testing and found the plug-in. I undid the work around on my system, so the only thing running is your fix. So far I haven’t noticed my controller acting up. Thanks so much for taking the time to do this! Searching for the solution also led me to xivlauncher, which has also been a godsend.
________________________________
